services:
  crazyswarm2-base:
    build: 
      context: ./
      target: crazyswarm2-base
    container_name: crazyswarm2-base
    environment:
      - DISPLAY=${DISPLAY}
      - FASTDDS_BUILTIN_TRANSPORTS=UDPv4
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix
      - ./ros2_ws:/root/ros2_ws
    devices:
      - /dev/input:/dev/input
      - /dev/dri:/dev/dri
    network_mode: "host"
    ipc: host
    # deploy:
    #   resources:
    #     reservations:
    #       devices:
    #         - driver: nvidia
    #           count: all
    #           capabilities: [gpu]
