services:
  crazyswarm-tests:
    build: 
      context: ./
      target: crazyswarm-tests
    container_name: crazyswarm-tests
    environment:
      - DISPLAY=${DISPLAY}
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix
      - ./ros2_ws:/root/ros2_ws
      # - ./crazyflie-firmware:/root/crazyflie-firmware
    devices:
      - /dev/input:/dev/input
      - /dev/dri:/dev/dri
    network_mode: "host"
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
